### ISSUE TITLE
Error when starting app once aurelia-validatejs added.

### ISSUE THREAD

**Issue by stevies** [aurelia/validatejs#19]
Using webpack.  Added `"aurelia-validatejs": "^0.2.0"` to package.json.  Added ` .plugin('aurelia-validatejs');` to main.js.  App fails to start with this error: 

>Unhandled rejection Error: Cannot find module './aurelia-validatejs/validate-binding-behavior'.
    at eval (webpack:///./src_^\.\/.*$?:104:41)
    at webpackContextResolve (webpack:///./src_^\.\/.*$?:104:89)
    at webpackContext (webpack:///./src_^\.\/.*$?:101:29)
    at eval (webpack:///./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js?:104:49)
    at http://localhost:3000/bundle.js:136:24
    at Function.requireEnsure [as e] (http://localhost:3000/bundle.js:597:29)
    at Function.ensure [as e] (http://localhost:3000/bundle.js:134:33)
    at eval (webpack:///./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js?:103:31)
    at Promise._execute (webpack:///./~/bluebird/js/browser/bluebird.js?:941:9)
    at Promise._resolveFromExecutor (webpack:///./~/bluebird/js/browser/bluebird.js?:3100:18)
    at new Promise (webpack:///./~/bluebird/js/browser/bluebird.js?:2704:14)
    at WebpackLoader._import (webpack:///./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js?:98:12)
    at eval (webpack:///./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js?:154:16)
    at Promise._execute (webpack:///./~/bluebird/js/browser/bluebird.js?:941:9)
    at Promise._resolveFromExecutor (webpack:///./~/bluebird/js/browser/bluebird.js?:3100:18)
    at new Promise (webpack:///./~/bluebird/js/browser/bluebird.js?:2704:14)
>

**Comment by stevies** [comment]
Here's the output from the webpack bundling.
`
    [0] multi main 52 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://localhost:3000 2.67 kB {0} [built]
    [2] ./~/url/url.js 22.3 kB {0} [built]
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] ./~/querystring/index.js 127 bytes {0} [built]
    [6] ./~/querystring/decode.js 2.4 kB {0} [built]
    [7] ./~/querystring/encode.js 2.09 kB {0} [built]
    [8] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
    [9] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [10] ./~/sockjs-client/lib/transport/websocket.js 2.68 kB {0} [built]
   [11] ./~/process/browser.js 2.06 kB {0} [built]
   [12] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
   [13] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [14] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [15] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
   [16] ./~/url-parse/index.js 8.09 kB {0} [built]
   [17] ./~/requires-port/index.js 753 bytes {0} [built]
   [18] ./~/url-parse/lolcation.js 1.58 kB {0} [built]
   [19] ./~/querystringify/index.js 1.3 kB {0} [built]
   [20] ./~/debug/browser.js 3.76 kB {0} [built]
   [21] ./~/debug/debug.js 4.1 kB {0} [built]
   [22] ./~/ms/index.js 2.33 kB {0} [built]
   [23] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
   [24] ./~/sockjs-client/lib/event/emitter.js 1.11 kB {0} [built]
   [25] ./~/sockjs-client/lib/event/eventtarget.js 1.75 kB {0} [built]
   [26] ./~/sockjs-client/lib/transport/browser/websocket.js 58 bytes {0} [built]
   [27] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [28] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
   [29] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {0} [built]
   [30] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
   [31] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [32] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [33] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
   [34] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.67 kB {0} [built]
   [35] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
   [36] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [37] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
   [38] ./~/sockjs-client/lib/transport/sender/xdr.js 2.42 kB {0} [built]
   [39] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [40] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
   [41] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [built]
   [42] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
   [43] ./~/sockjs-client/lib/transport/iframe.js 3.8 kB {0} [built]
   [44] ./~/sockjs-client/~/json3/lib/json3.js 43.3 kB {0} [built]
   [45] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [46] ./~/sockjs-client/lib/version.js 25 bytes {0} [built]
   [47] ./~/sockjs-client/lib/utils/iframe.js 4.95 kB {0} [built]
   [48] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [49] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [50] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.17 kB {0} [built]
   [51] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [52] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [53] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [54] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.49 kB {0} [built]
   [55] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [56] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [57] ./~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
   [58] ./~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
   [59] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [60] ./~/sockjs-client/lib/utils/log.js 386 bytes {0} [built]
   [61] ./~/sockjs-client/lib/event/event.js 485 bytes {0} [built]
   [62] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [63] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [64] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [65] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [66] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
   [67] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [68] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [69] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [70] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [71] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [72] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [73] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [74] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
   [75] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]
   [76] ./src/main.js 637 bytes {0} [built]
   [77] ./~/aurelia-bootstrapper-webpack/dist/commonjs/aurelia-bootstrapper-webpack.js 2.5 kB {0} [built]
   [78] ./~/bluebird/js/browser/bluebird.js 173 kB {0} [built]
   [79] ./~/timers-browserify/main.js 2.1 kB {0} [built]
   [80] ./~/aurelia-polyfills/dist/commonjs/aurelia-polyfills.js 21.3 kB {0} [built]
   [81] ./~/aurelia-pal/dist/commonjs/aurelia-pal.js 1.47 kB {0} [built]
   [82] ./~/aurelia-pal-browser/dist/commonjs/aurelia-pal-browser.js 13.8 kB {0} [built]
   [83] ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js 5.76 kB {0} [built]
   [84] ./~/aurelia-metadata/dist/commonjs/aurelia-metadata.js 6.8 kB {0} [built]
   [85] ./~/aurelia-loader/dist/commonjs/aurelia-loader.js 4.85 kB {0} [built]
   [86] ./~/aurelia-path/dist/commonjs/aurelia-path.js 5.45 kB {0} [built]
  [139] ./~/aurelia-validatejs/dist/commonjs/index.js 3.05 kB {0} [built]
  [140] ./~/aurelia-validatejs/dist/commonjs/decorators.js 2.51 kB {0} [built]
  [141] ./~/aurelia-validatejs/dist/commonjs/base-decorator.js 1.35 kB {0} [built]
  [142] ./~/aurelia-validatejs/dist/commonjs/validation-config.js 1.31 kB {0} [built]
  [143] ./~/aurelia-validatejs/dist/commonjs/validation-engine.js 732 bytes {0} [built]
  [144] ./~/aurelia-validatejs/dist/commonjs/validation-reporter.js 1.95 kB {0} [built]
  [145] ./~/aurelia-validation/dist/commonjs/index.js 744 bytes {0} [built]
  [146] ./~/aurelia-validation/dist/commonjs/validator.js 657 bytes {0} [built]
  [147] ./~/aurelia-validation/dist/commonjs/validation-reporter.js 1.18 kB {0} [built]
  [148] ./~/aurelia-validation/dist/commonjs/validation-engine.js 732 bytes {0} [built]
  [149] ./~/aurelia-validatejs/dist/commonjs/rules/length.js 493 bytes {0} [built]
  [150] ./~/aurelia-validatejs/dist/commonjs/validation-rule.js 1.29 kB {0} [built]
  [151] ./~/validate.js/validate.js 32.9 kB {0} [built]
  [152] (webpack)/buildin/amd-define.js 85 bytes {0} [built]
  [153] ./~/aurelia-validatejs/dist/commonjs/validation-error.js 616 bytes {0} [built]
  [154] ./~/aurelia-validatejs/dist/commonjs/rules/required.js 497 bytes {0} [built]
  [155] ./~/aurelia-validatejs/dist/commonjs/rules/date.js 473 bytes {0} [built]
  [156] ./~/aurelia-validatejs/dist/commonjs/rules/datetime.js 497 bytes {0} [built]
  [157] ./~/aurelia-validatejs/dist/commonjs/rules/email.js 479 bytes {0} [built]
  [158] ./~/aurelia-validatejs/dist/commonjs/rules/equality.js 505 bytes {0} [built]
  [159] ./~/aurelia-validatejs/dist/commonjs/rules/exclusion.js 511 bytes {0} [built]
  [160] ./~/aurelia-validatejs/dist/commonjs/rules/inclusion.js 511 bytes {0} [built]
  [161] ./~/aurelia-validatejs/dist/commonjs/rules/format.js 493 bytes {0} [built]
  [162] ./~/aurelia-validatejs/dist/commonjs/rules/url.js 467 bytes {0} [built]
  [163] ./~/aurelia-validatejs/dist/commonjs/rules/numericality.js 614 bytes {0} [built]
  [164] ./~/aurelia-validatejs/dist/commonjs/validator.js 3.77 kB {0} [built]
  [165] ./~/aurelia-validatejs/dist/commonjs/validation-renderer.js 1.71 kB {0} [built]
  [171] ./styles/styles.scss 1.09 kB {0} [built]
  [172] ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./styles/styles.scss 973 bytes {0} [built]
  [173] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
  [174] ./styles/images/sgov-logo.png 82 bytes {0} [built]
  [175] ./~/style-loader/addStyles.js 7.15 kB {0} [built]
chunk    {1} 1.bundle.js 818 kB {0} [rendered]
   [87] ./src ^\.\/.*$ 4.34 kB {1} [optional] [built]
   [88] ./src/app.js 692 bytes {1} [optional] [built]
   [89] ./src/app.html 368 bytes {1} [optional] [built]
   [90] ./~/aurelia-event-aggregator/dist/commonjs/aurelia-event-aggregator.js 3.52 kB {1} [built]
   [91] ./~/aurelia-logging/dist/commonjs/aurelia-logging.js 2.3 kB {1} [built]
   [92] ./~/aurelia-fetch-client/dist/commonjs/aurelia-fetch-client.js 7.69 kB {1} [built]
   [93] ./~/aurelia-framework/dist/commonjs/aurelia-framework.js 16.6 kB {1} [built]
   [94] ./~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js 17.9 kB {1} [built]
   [95] ./~/aurelia-binding/dist/commonjs/aurelia-binding.js 167 kB {1} [built]
   [96] ./~/aurelia-task-queue/dist/commonjs/aurelia-task-queue.js 3.4 kB {1} [built]
   [97] ./~/aurelia-templating/dist/commonjs/aurelia-templating.js 131 kB {1} [built]
   [98] ./~/aurelia-history-browser/dist/commonjs/aurelia-history-browser.js 9.3 kB {1} [built]
   [99] ./~/aurelia-history/dist/commonjs/aurelia-history.js 1 kB {1} [built]
  [100] ./~/aurelia-logging-console/dist/commonjs/aurelia-logging-console.js 3.1 kB {1} [built]
  [101] ./~/aurelia-router/dist/commonjs/aurelia-router.js 52 kB {1} [built]
  [102] ./~/aurelia-route-recognizer/dist/commonjs/aurelia-route-recognizer.js 11.7 kB {1} [built]
  [103] ./~/aurelia-templating-binding/dist/commonjs/aurelia-templating-binding.js 22 kB {1} [built]
  [104] ./~/aurelia-templating-resources/dist/commonjs/aurelia-templating-resources.js 4.86 kB {1} [built]
  [105] ./~/aurelia-templating-resources/dist/commonjs/compose.js 6.4 kB {1} [built]
  [106] ./~/aurelia-templating-resources/dist/commonjs/if.js 3.14 kB {1} [built]
  [107] ./~/aurelia-templating-resources/dist/commonjs/with.js 1.73 kB {1} [built]
  [108] ./~/aurelia-templating-resources/dist/commonjs/repeat.js 9.89 kB {1} [built]
  [109] ./~/aurelia-templating-resources/dist/commonjs/repeat-strategy-locator.js 1.96 kB {1} [built]
  [110] ./~/aurelia-templating-resources/dist/commonjs/null-repeat-strategy.js 668 bytes {1} [built]
  [111] ./~/aurelia-templating-resources/dist/commonjs/array-repeat-strategy.js 6.18 kB {1} [built]
  [112] ./~/aurelia-templating-resources/dist/commonjs/repeat-utilities.js 2.69 kB {1} [built]
  [113] ./~/aurelia-templating-resources/dist/commonjs/map-repeat-strategy.js 3.75 kB {1} [built]
  [114] ./~/aurelia-templating-resources/dist/commonjs/set-repeat-strategy.js 3.17 kB {1} [built]
  [115] ./~/aurelia-templating-resources/dist/commonjs/number-repeat-strategy.js 1.94 kB {1} [built]
  [116] ./~/aurelia-templating-resources/dist/commonjs/analyze-view-factory.js 1.7 kB {1} [built]
  [117] ./~/aurelia-templating-resources/dist/commonjs/abstract-repeater.js 1.7 kB {1} [built]
  [118] ./~/aurelia-templating-resources/dist/commonjs/show.js 1.2 kB {1} [built]
  [119] ./~/aurelia-templating-resources/dist/commonjs/hide.js 1.2 kB {1} [built]
  [120] ./~/aurelia-templating-resources/dist/commonjs/sanitize-html.js 1.19 kB {1} [built]
  [121] ./~/aurelia-templating-resources/dist/commonjs/html-sanitizer.js 587 bytes {1} [built]
  [122] ./~/aurelia-templating-resources/dist/commonjs/replaceable.js 1.32 kB {1} [built]
  [123] ./~/aurelia-templating-resources/dist/commonjs/focus.js 2.01 kB {1} [built]
  [124] ./~/aurelia-templating-resources/dist/commonjs/compile-spy.js 1.27 kB {1} [built]
  [125] ./~/aurelia-templating-resources/dist/commonjs/view-spy.js 1.77 kB {1} [built]
  [126] ./~/aurelia-templating-resources/dist/commonjs/css-resource.js 4.11 kB {1} [built]
  [127] ./~/aurelia-templating-resources/dist/commonjs/binding-mode-behaviors.js 1.64 kB {1} [built]
  [128] ./~/aurelia-templating-resources/dist/commonjs/throttle-binding-behavior.js 2.12 kB {1} [built]
  [129] ./~/aurelia-templating-resources/dist/commonjs/debounce-binding-behavior.js 1.93 kB {1} [built]
  [130] ./~/aurelia-templating-resources/dist/commonjs/signal-binding-behavior.js 2.07 kB {1} [built]
  [131] ./~/aurelia-templating-resources/dist/commonjs/binding-signaler.js 775 bytes {1} [built]
  [132] ./~/aurelia-templating-resources/dist/commonjs/update-trigger-binding-behavior.js 2.09 kB {1} [built]
  [133] ./~/aurelia-templating-resources/dist/commonjs/html-resource-plugin.js 1.2 kB {1} [built]
  [134] ./~/aurelia-templating-resources/dist/commonjs/dynamic-element.js 1.02 kB {1} [built]
  [135] ./~/aurelia-templating-router/dist/commonjs/aurelia-templating-router.js 862 bytes {1} [built]
  [136] ./~/aurelia-templating-router/dist/commonjs/route-loader.js 2.69 kB {1} [built]
  [137] ./~/aurelia-templating-router/dist/commonjs/router-view.js 6.76 kB {1} [built]
  [138] ./~/aurelia-templating-router/dist/commonjs/route-href.js 2.53 kB {1} [built]
  [166] ./src/banner.html 790 bytes {1} [optional] [built]
  [167] ./src/footer-area.html 967 bytes {1} [optional] [built]
  [168] ./~/isomorphic-fetch/fetch-npm-browserify.js 233 bytes {1} [built]
  [169] ./~/whatwg-fetch/fetch.js 11.6 kB {1} [built]
  [170] ./~/jquery/dist/jquery.js 259 kB {1} [built]
  [176] ./src/nav-bar.html 391 bytes {1} [optional] [built]
  [177] ./src/resources/converters/capitaliseFirst.js 633 bytes {1} [optional] [built]
  [178] ./src/resources/index.js 163 bytes {1} [optional] [built]
  [179] ./src/views/welcome.js 1.17 kB {1} [optional] [built]
  [180] ./src/views/welcome.html 119 bytes {1} [optional] [built]
`

**Comment by mbroadst** [comment]
@stevies you need to make sure to add `aurelia-validatejs` to your `includeSubModules` in the webpack configuration, e.g.: 

```
  plugins: [
    new AureliaWebpackPlugin({
      includeSubModules: [
        { moduleId: 'aurelia-auth' },
        { moduleId: 'aurelia-validatejs' }
      ]
    })
  ],
```

Unless @MartijnBoland has plans to add it to the default submodules, then this will be the case for the foreseeable future.

HTH

**Comment by stevies** [comment]
I have now added this: 
```javascript
    plugins: [
          new AureliaWebpackPlugin({
              includeSubModules: [
                  {moduleId: 'aurelia-validatejs'}
              ]
          }),
          ...
      ],
```
Still gives the same error when starting the app.  
`Unhandled rejection Error: Cannot find module './aurelia-validatejs/validate-binding-behavior'.`
Anything else I am missing?

**Comment by mbroadst** [comment]
@stevies if you're using webpack watch you will need to stop that process and restart it in order to reflect the changes to the config. If that's not the problem, perhaps you could post your entire webpack config seems like you have some sort of configuration error. This works fine for me.

**Comment by stevies** [comment]
Yes - stopping and starting the watcher appears to have fixed it.  Thanks.

**Comment by mikeesouth** [comment]
Should we still use this with @easy-webpack and the other changes that have been committed to the skeleton repo since May? I'm also getting this error with Aurelia RC.
