### ISSUE TITLE
Cannot build the code

### ISSUE THREAD

**Issue by iveetoo** [aurelia/validatejs#44]
When I install the dev dependencies I got a warning:
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12`

Then, when I run `gulp build` I got the following error:

` events.js:160
      throw er; // Unhandled 'error' event
      ^
 TypeError: D:/dev/projects/validatejs/dist/aurelia-validatejs.js: Duplicate declaration "ValidationError"
←[0m  37 | ←[32m}←[39m
  38 |
> 39 | ←[36mexport←[39m ←[36mclass←[39m ValidationError ←[32m{←[39m
     |              ^
  40 |   message ←[1m=←[22m ←[31m''←[39m←[1m;←[22m
  41 |   object←[1m;←[22m
  42 |   propertyName ←[1m=←[22m ←[31m''←[39m←[1m;←[22m←[0m
    at File.buildCodeFrameError (D:\dev\projects\validatejs\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\index.js:467:15)
    at Scope.checkBlockScopedCollisions (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\scope\index.js:490:27)
    at Scope.registerBinding (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\scope\index.js:679:16)
    at Scope.registerDeclaration (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\scope\index.js:581:12)
    at Object.BlockScoped (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\scope\index.js:217:28)
    at Object.newFn (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\visitors.js:343:17)
    at NodePath._call (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\path\context.js:78:18)
    at NodePath.call (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\path\context.js:45:14)
    at NodePath.visit (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\path\context.js:108:12)
    at TraversalContext.visitQueue (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\context.js:174:16)
    at TraversalContext.visitSingle (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\context.js:124:19)
    at TraversalContext.visit (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\context.js:219:19)
    at Function.traverse.node (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\index.js:171:17)
    at NodePath.visit (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\path\context.js:118:43)
    at TraversalContext.visitQueue (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\context.js:174:16)
    at TraversalContext.visitMultiple (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\context.js:119:17)
    at TraversalContext.visit (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\context.js:217:19)
    at Function.traverse.node (D:\dev\projects\validatejs\node_modules\babel-traverse\lib\index.js:171:17)`

I figured out that the error is caused by `build-es2015-temp` task. I tried on Windows7 and Node versions 6.1.0 and 5.6.0

**Comment by iveetoo** [comment]
The code is built with the new release.
